### ISSUE TITLE
Prepare release

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/json-logic-js#12]
**Todo:**

- [x] Bump version number within `package.json`
- [x] make sure that this package is defined inside `@axa-ch` organisation within `package.json`
- [ ] maybe add the release script 🤔
- [ ] maybe add `develop` branch
